version: '3.8'
services:
   web:
       build: .
       container_name: c1_bigdata
       command: bash -c "python src/train.py && python src/predict.py -m && coverage run src/unit_tests/test_preprocess.py && coverage run -a src/unit_tests/test_training.py && coverage report -m"
       ports:
           - 8000:8000
       image: liaox1/big_data:1.0